# Generated by Django 4.1.2 on 2022-10-31 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp03", "0003_alter_board_writer_alter_comment_writer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Webtoond",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=600)),
                ("writer", models.TextField(null=True)),
                ("score", models.IntegerField(default=0)),
            ],
        ),
    ]
