# Generated by Django 4.1.2 on 2022-10-31 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp03", "0004_webtoond"),
    ]

    operations = [
        migrations.RenameModel(old_name="Webtoond", new_name="Webtoon",),
    ]
