# Generated by Django 4.1.2 on 2022-10-31 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp03", "0005_rename_webtoond_webtoon"),
    ]

    operations = [
        migrations.AddField(
            model_name="webtoon",
            name="webDay",
            field=models.CharField(default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="webtoon", name="title", field=models.TextField(null=True),
        ),
    ]
