# Generated by Django 4.1.2 on 2022-10-31 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp03", "0006_webtoon_webday_alter_webtoon_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webtoon", name="score", field=models.FloatField(default=0),
        ),
    ]
